### PR TITLE
util.lua table.compare optimization

### PR DESCRIPTION
**Pull request by sparr**
the current implementation performs the same element comparisons repeatedly, when we really just need to check if tbl2 contains any keys that tbl1 does not, because recursive comparison has already been done for the keys they both contain.

https://forums.factorio.com/viewtopic.php?f=28&t=59358

### CODE REVIEW

**Comment by Klonan** [comment]
We don't take PR's on this repo

**Comment by Katamori** [comment]
@Klonan then you should specify it in the README.

**Comment by dgw** [comment]
And all of us should vote for (and maybe contact GitHub support expressing a desire for) isaacs/github#1191 and/or dear-github/dear-github#84

**Comment by SuperSandro2000** [comment]
Take the improvement anyway.

**Comment by sparr** [comment]
They did already implement this, in 0.17.0
https://github.com/wube/factorio-data/blame/master/core/lualib/util.lua#L37

**Pull request closed without merging**
